# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shatel_app', '0002_mgwabzkrjraw_mgwarbpcraw_mgwboubhmnraw_mgwcmbpcraw_mgwesfemam1raw_mgwesfemam2raw_mgwfrsvaliraw_mgwgl'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaBcfCdr',
            fields=[
                ('stime', models.DateTimeField(blank=True, null=True)),
                ('ocgpn', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('ocdpn', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('s_trunk', models.TextField(blank=True, null=True)),
                ('d_trunk', models.TextField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('call', models.TextField(blank=True, null=True)),
                ('crinfo', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('action_v', models.TextField(blank=True, null=True)),
                ('direction', models.TextField(blank=True, null=True)),
                ('s_ip', models.TextField(blank=True, null=True)),
                ('d_ip', models.TextField(blank=True, null=True)),
                ('s_name', models.TextField(blank=True, null=True)),
                ('d_name', models.TextField(blank=True, null=True)),
                ('sss', models.TextField(blank=True, null=True)),
                ('blank', models.TextField(blank=True, null=True)),
                ('blank2', models.TextField(blank=True, null=True)),
                ('a', models.TextField(blank=True, null=True)),
                ('b', models.TextField(blank=True, null=True)),
                ('c', models.TextField(blank=True, null=True)),
                ('caller', models.TextField(blank=True, null=True)),
                ('called', models.TextField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ava_bcf_cdr',
                'managed': False,
            },
        ),
    ]
