# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models



class MgwAbzKrjRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_abz_krj_raw'


class MgwArbPcRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_arb_pc_raw'


class MgwBouBhmnRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_bou_bhmn_raw'


class MgwCmbPcRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_cmb_pc_raw'


class MgwEsfEmam1Raw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_esf_emam1_raw'


class MgwEsfEmam2Raw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_esf_emam2_raw'


class MgwFrsValiRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_frs_vali_raw'


class MgwGlnGlsrRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_gln_glsr_raw'


class MgwGrnEmamRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_grn_emam_raw'


class MgwHamTaher2Raw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_ham_taher2_raw'


class MgwHamTaherRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_ham_taher_raw'


class MgwHmnEaliRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_hmn_eali_raw'


class MgwKhrFrsh2Raw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_khr_frsh2_raw'


class MgwKhrFrshRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_khr_frsh_raw'


class MgwKhsPcRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_khs_pc_raw'


class MgwKhzVali1Raw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_khz_vali1_raw'


class MgwKhzVali2Raw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_khz_vali2_raw'


class MgwKorSanRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_kor_san_raw'


class MgwKrmVasrRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_krm_vasr_raw'


class MgwMznEmam1Raw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_mzn_emam1_raw'


class MgwMznEmam2Raw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_mzn_emam2_raw'


class MgwOurMdrsRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_our_mdrs_raw'


class MgwQomQomRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_qom_qom_raw'


class MgwSmnAmloRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_smn_amlo_raw'


class MgwTabRhmiRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_tab_rhmi_raw'


class MgwTehIsc2Raw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_teh_isc2_raw'


class MgwTehSc22Raw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_teh_sc22_raw'


class MgwYzdSadqRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_yzd_sadq_raw'


class MgwZnjPcRaw(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.TextField(blank=True, null=True)
    ocdpn = models.TextField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_znj_pc_raw'
