# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models

class AvaBcfCdr(models.Model):
    stime = models.DateTimeField(blank=True, null=True)
    ocgpn = models.DecimalField(max_digits=65535, decimal_places=0, blank=True, null=True)
    ocdpn = models.DecimalField(max_digits=65535, decimal_places=0, blank=True, null=True)
    s_trunk = models.TextField(blank=True, null=True)
    d_trunk = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    call = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    action = models.TextField(blank=True, null=True)
    action_v = models.TextField(blank=True, null=True)
    direction = models.TextField(blank=True, null=True)
    s_ip = models.TextField(blank=True, null=True)
    d_ip = models.TextField(blank=True, null=True)
    s_name = models.TextField(blank=True, null=True)
    d_name = models.TextField(blank=True, null=True)
    sss = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    a = models.TextField(blank=True, null=True)
    b = models.TextField(blank=True, null=True)
    c = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'ava_bcf_cdr'


class MgwAbzKrj(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_abz_krj'


class MgwArbPc(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_arb_pc'


class MgwBouBhmn(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_bou_bhmn'


class MgwCmbPc(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_cmb_pc'


class MgwEsfEmam1(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_esf_emam1'


class MgwEsfEmam2(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_esf_emam2'


class MgwFrsVali(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_frs_vali'


class MgwGlnGlsr(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_gln_glsr'


class MgwGrnEmam(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_grn_emam'


class MgwHamTaher(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_ham_taher'


class MgwHamTaher2(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_ham_taher2'


class MgwHmnEali(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_hmn_eali'


class MgwKhrFrsh(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_khr_frsh'


class MgwKhrFrsh2(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_khr_frsh2'


class MgwKhsPc(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_khs_pc'


class MgwKhzVali1(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_khz_vali1'


class MgwKhzVali2(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_khz_vali2'


class MgwKorSan(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_kor_san'


class MgwKrmVasr(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_krm_vasr'


class MgwMznEmam1(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_mzn_emam1'


class MgwMznEmam2(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_mzn_emam2'


class MgwOurMdrs(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_our_mdrs'


class MgwQomQom(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_qom_qom'


class MgwSmnAmlo(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_smn_amlo'


class MgwTabRhmi(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_tab_rhmi'


class MgwTehIsc2(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_teh_isc2'


class MgwTehSc21(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_teh_sc21'


class MgwTehSc22(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_teh_sc22'


class MgwYzdSadq(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_yzd_sadq'


class MgwZnjPc(models.Model):
    sign = models.TextField(blank=True, null=True)
    stime = models.DateTimeField(blank=True, null=True)
    ctime = models.TextField(blank=True, null=True)
    dtime = models.TextField(blank=True, null=True)
    duration = models.FloatField(blank=True, null=True)
    icgpn = models.TextField(blank=True, null=True)
    icdpn = models.TextField(blank=True, null=True)
    ocgpn = models.BigIntegerField(blank=True, null=True)
    ocdpn = models.BigIntegerField(blank=True, null=True)
    pmark = models.TextField(blank=True, null=True)
    irnumber = models.TextField(blank=True, null=True)
    ornumber = models.TextField(blank=True, null=True)
    rmark = models.TextField(blank=True, null=True)
    iipaddress = models.TextField(blank=True, null=True)
    oipaddress = models.TextField(blank=True, null=True)
    itype = models.TextField(blank=True, null=True)
    otype = models.TextField(blank=True, null=True)
    release_cause = models.TextField(blank=True, null=True)
    rsmark = models.TextField(blank=True, null=True)
    crinfo = models.TextField(blank=True, null=True)
    idesc = models.TextField(blank=True, null=True)
    odesc = models.TextField(blank=True, null=True)
    ie1ch = models.TextField(blank=True, null=True)
    oe1ch = models.TextField(blank=True, null=True)
    ie1str = models.TextField(blank=True, null=True)
    oe1str = models.TextField(blank=True, null=True)
    iss7cat = models.TextField(blank=True, null=True)
    oss7cat = models.TextField(blank=True, null=True)
    iss7cic = models.TextField(blank=True, null=True)
    oss7cic = models.TextField(blank=True, null=True)
    icid = models.TextField(blank=True, null=True)
    ocid = models.TextField(blank=True, null=True)
    blank = models.TextField(blank=True, null=True)
    blank2 = models.TextField(blank=True, null=True)
    blank3 = models.TextField(blank=True, null=True)
    caller = models.TextField(blank=True, null=True)
    called = models.TextField(blank=True, null=True)
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'mgw_znj_pc'
